# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuw5x1HomwSQLfTCX14Be2Y4-Ppu8wIo
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy.optimize import linear_sum_assignment

# Load the dataset
@st.cache_data
def load_data():
    # Load the uploaded dataset
    file_path = "/content/ITsupport.csv"
    data = pd.read_csv(file_path)


    # Ensure required columns are present
    required_columns = ['Ticket ID', 'User ID', 'Issue Type', 'Status', 'Assigned Agent', 'Priority']
    for col in required_columns:
        if col not in data.columns:
            data[col] = 'Unknown'  # Add missing columns if needed

    return data

# Hungarian Method for Optimal Assignment
def assign_agents(data):
    # Generate a sample cost matrix for demonstration
    cost_matrix = np.random.randint(1, 20, size=(len(data), 3))
    row_ind, col_ind = linear_sum_assignment(cost_matrix)

    # Assign agents based on Hungarian method
    for i, ticket_id in enumerate(data['Ticket ID']):
        data.loc[i, 'Assigned Agent'] = f"Agent {col_ind[i] + 1}"

    return data

# Streamlit App Layout
st.title("🚨 IT Support System - Ticket Management")

# Load dataset
data = load_data()

# Display tickets
st.subheader("📋 Current Support Tickets")
st.dataframe(data)

# Ticket Submission Form
st.subheader("➕ Submit a New Support Ticket")
with st.form(key='ticket_form'):
    user_id = st.text_input("User ID", value="")
    issue_type = st.text_input("Issue Type", value="")
    priority = st.selectbox("Priority", ["Low", "Medium", "High"])

    submitted = st.form_submit_button("Submit Ticket")
    if submitted:
        new_ticket = pd.DataFrame({
            'Ticket ID': [f"T{len(data) + 1}"],
            'User ID': [user_id],
            'Issue Type': [issue_type],
            'Status': ['Open'],
            'Assigned Agent': ['Unassigned'],
            'Priority': [priority]
        })
        data = pd.concat([data, new_ticket], ignore_index=True)
        st.success("✅ Ticket submitted successfully!")

# Assign Agents Using Hungarian Method
if st.button("🔄 Assign Agents Using Hungarian Method"):
    data = assign_agents(data)
    st.success("✅ Agents assigned successfully!")
    st.dataframe(data)

# Display Final Ticket Data
st.subheader("📌 Updated Ticket Information")
st.dataframe(data)

import os
print(os.listdir('.'))  # For current directory
print(os.listdir('/content'))  # For Colab root directory